# package overview 
package_name: "credit-risk"

# datafiles 
raw_data_file: ../../data/raw/accepted_2007_to_2018Q4.csv

# X train file path 

X_train_file: ../../data/interim/xtrain.csv

# X test file path 

X_test_file: ../../data/interim/xtest.csv

# y train file path 

y_train_file: ../../data/interim/ytrain.csv

# y test file path 

y_test_file: ../../data/interim/ytest.csv

# variables 
target: loan_status 

pipeline_name: final_model

# test size 
test_size: 0.20 

# random state 
random_state: 42

# model params 
class_ratio: 3.6572525177046007

scale_pos_weight: 3.6572525177046007

n_estimators: 177

booster: 'gbtree'

learning_rate: 0.01005215884865718

max_depth: 1

min_child_weight: 3

objective: 'binary:logistic'

# finalised features 
features: 
- int_rate
- fico_range_high
- inq_last_6mths
- open_il_12m
- acc_open_past_24mths
- mort_acc
- num_tl_op_past_12m
- percent_bc_gt_75
- term
- sub_grade

numerical_features: 
- int_rate
- fico_range_high
- inq_last_6mths
- open_il_12m
- acc_open_past_24mths
- mort_acc
- num_tl_op_past_12m
- percent_bc_gt_75

categorical_features: 
- term 
- sub_grade

categorical_features_to_encode_one_hot: 
- term 

categorical_features_to_encode_ordinally: 
- sub_grade

target_mappings: 
  Charged Off: 1
  Fully Paid: 0
